name: Docs Check
on:
  push:
    branches:
      - '!dev'
      - '!master'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation.yml'

jobs:
  docs:
    name: Check Documentation
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout D++
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Docs
        run: cd docpages && php makedocs-gh.php nodeploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

